default_context:
    repo_name: "pip_repo"
    project_name: "project_name"
    deps_manager: "pip"
    use_aws: "aws"
    use_logging: "y"
    author_name: "author_name"
    description: "description"
    python_version: "3.12"
    open_source_license: "MIT"
