default_context:
    repo_name: "uv_repo"
    project_name: "project_name"
    deps_manager: "uv"
    author_name: "author_name"
    description: "description"
    python_version: "3.12"
    open_source_license: "MIT"
