name: Check Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    name: Template generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{cookiecutter.python_version}}"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install invoke
          invoke requirements
          pip list

      - name: Execute template
        run: |
          invoke template

      - name: Generated tree structure
        run: |
          tree -a repo

      - name: Upload generated templates
        uses: actions/upload-artifact@v4
        with:
          name: generated-template
          path: |
            repo
          include-hidden-files: true

  project:
    name: Project
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download generated template
        uses: actions/download-artifact@v4
        with:
          name: generated-template
          path: repo

      - name: Artifact structure
        run: tree -a repo

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install project dependencies
        run: |
          cd repo
          pip install invoke
          invoke create-environment
          invoke requirements
          invoke dev-requirements
        env:
          TERM: xterm

      - name: List all project commands
        run: |
          cd repo
          invoke --list

      - name: Run project commands
        run: |
          cd repo
          invoke preprocess-data
          invoke train
          invoke test
        env:
          TERM: xterm

      - name: Build documentation
        run: |
          cd repo
          invoke build-docs
        env:
          TERM: xterm

      - name: Build dockerfiles
        run: |
          cd repo
          invoke docker-build
        env:
          TERM: xterm

      - name: Check devcontainer
        run: |
          cd repo
          npx @devcontainers/cli build --workspace-folder .
          npx @devcontainers/cli up --workspace-folder .
        env:
          TERM: xterm
