name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  template:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{cookiecutter.python_version}}"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Run tests
        run: |
          pytest tests/
